#!/bin/bash
#===============================================================================
# WURM-TOOLS VPS Security Hardening Script
# For Ubuntu 22.04/24.04 LTS on OVH VPS
#
# This script configures:
# - UFW Firewall
# - Fail2Ban (brute-force protection)
# - SSH hardening
# - Automatic security updates
# - System hardening
#
# Usage: sudo bash 02-security-setup.sh
#===============================================================================

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SSH_PORT="${SSH_PORT:-22}"
ADMIN_EMAIL="${ADMIN_EMAIL:-}"

#===============================================================================
# Helper Functions
#===============================================================================

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_banner() {
    echo -e "${RED}"
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║                                                            ║"
    echo "║   ███████╗███████╗ ██████╗██╗   ██╗██████╗ ██╗████████╗   ║"
    echo "║   ██╔════╝██╔════╝██╔════╝██║   ██║██╔══██╗██║╚══██╔══╝   ║"
    echo "║   ███████╗█████╗  ██║     ██║   ██║██████╔╝██║   ██║      ║"
    echo "║   ╚════██║██╔══╝  ██║     ██║   ██║██╔══██╗██║   ██║      ║"
    echo "║   ███████║███████╗╚██████╗╚██████╔╝██║  ██║██║   ██║      ║"
    echo "║   ╚══════╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚═╝   ╚═╝      ║"
    echo "║                                                            ║"
    echo "║          Security Hardening Script v1.0                    ║"
    echo "║                                                            ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        log_error "Please run as root (sudo bash $0)"
        exit 1
    fi
}

#===============================================================================
# UFW Firewall Setup
#===============================================================================

setup_firewall() {
    log_info "Configuring UFW firewall..."

    # Install UFW if not present
    apt install -y ufw

    # Reset UFW to defaults
    ufw --force reset

    # Set default policies
    ufw default deny incoming
    ufw default allow outgoing

    # Allow SSH (important: do this first!)
    ufw allow ${SSH_PORT}/tcp comment 'SSH'

    # Allow HTTP and HTTPS
    ufw allow 80/tcp comment 'HTTP'
    ufw allow 443/tcp comment 'HTTPS'

    # Rate limit SSH connections (max 6 connections per 30 seconds)
    ufw limit ${SSH_PORT}/tcp comment 'SSH rate limit'

    # Enable UFW
    ufw --force enable

    log_success "UFW firewall configured and enabled"
}

#===============================================================================
# Fail2Ban Setup
#===============================================================================

setup_fail2ban() {
    log_info "Installing and configuring Fail2Ban..."

    apt install -y fail2ban

    # Create custom jail configuration
    cat > /etc/fail2ban/jail.local <<'EOF'
[DEFAULT]
# Ban duration (10 minutes default, increases with each ban)
bantime = 10m
bantime.increment = true
bantime.factor = 2
bantime.maxtime = 1w

# Time window for failures
findtime = 10m

# Number of failures before ban
maxretry = 5

# Use UFW for banning
banaction = ufw

# Ignore local IPs
ignoreip = 127.0.0.1/8 ::1

# Email notifications (if configured)
# destemail = admin@example.com
# sender = fail2ban@example.com
# action = %(action_mwl)s

[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 1h

[sshd-ddos]
enabled = true
port = ssh
filter = sshd-ddos
logpath = /var/log/auth.log
maxretry = 6
bantime = 1h

[nginx-http-auth]
enabled = false

[nginx-limit-req]
enabled = false

[nginx-botsearch]
enabled = false

# Caddy doesn't have built-in fail2ban support
# but we protect at the SSH level
EOF

    # Restart Fail2Ban
    systemctl restart fail2ban
    systemctl enable fail2ban

    log_success "Fail2Ban configured and running"
}

#===============================================================================
# SSH Hardening
#===============================================================================

harden_ssh() {
    log_info "Hardening SSH configuration..."

    # Backup original config
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d)

    # Create hardened SSH config
    cat > /etc/ssh/sshd_config.d/99-hardening.conf <<EOF
# SSH Hardening Configuration
# Generated by WURM-TOOLS security script

# Disable root login (use regular user + sudo)
PermitRootLogin prohibit-password

# Disable password authentication (use SSH keys only)
# Uncomment after setting up SSH keys:
# PasswordAuthentication no

# Use strong key exchange algorithms
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512

# Use strong ciphers
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com

# Use strong MACs
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com

# Disable empty passwords
PermitEmptyPasswords no

# Disable X11 forwarding
X11Forwarding no

# Disable TCP forwarding (if not needed)
AllowTcpForwarding no

# Disable agent forwarding
AllowAgentForwarding no

# Set login grace time
LoginGraceTime 30

# Maximum authentication attempts
MaxAuthTries 3

# Maximum sessions
MaxSessions 3

# Client alive settings (disconnect idle sessions after 10 min)
ClientAliveInterval 300
ClientAliveCountMax 2

# Disable compression
Compression no

# Log level
LogLevel VERBOSE
EOF

    # Test SSH config
    if sshd -t; then
        systemctl reload sshd
        log_success "SSH hardened successfully"
    else
        log_error "SSH config test failed, reverting..."
        rm /etc/ssh/sshd_config.d/99-hardening.conf
        exit 1
    fi

    log_warning "Consider setting up SSH keys and disabling password auth"
}

#===============================================================================
# Automatic Security Updates
#===============================================================================

setup_auto_updates() {
    log_info "Configuring automatic security updates..."

    apt install -y unattended-upgrades apt-listchanges

    # Configure unattended-upgrades
    cat > /etc/apt/apt.conf.d/50unattended-upgrades <<'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};

// Remove unused kernel packages
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";

// Remove unused dependencies
Unattended-Upgrade::Remove-Unused-Dependencies "true";

// Automatic reboot if required (at 3 AM)
Unattended-Upgrade::Automatic-Reboot "true";
Unattended-Upgrade::Automatic-Reboot-Time "03:00";

// Clean up old packages
Unattended-Upgrade::AutoFixInterruptedDpkg "true";
EOF

    # Enable auto-upgrades
    cat > /etc/apt/apt.conf.d/20auto-upgrades <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
EOF

    systemctl enable unattended-upgrades
    systemctl restart unattended-upgrades

    log_success "Automatic security updates enabled"
}

#===============================================================================
# System Hardening
#===============================================================================

harden_system() {
    log_info "Applying system hardening..."

    # Kernel hardening via sysctl
    cat > /etc/sysctl.d/99-security.conf <<'EOF'
# Network security
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# IPv6 security
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# TCP SYN flood protection
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 5

# Disable ICMP redirects
net.ipv4.icmp_ignore_bogus_error_responses = 1
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Prevent IP spoofing
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Disable IP forwarding (unless needed for Docker)
net.ipv4.ip_forward = 0
net.ipv6.conf.all.forwarding = 0

# Kernel hardening
kernel.randomize_va_space = 2
kernel.kptr_restrict = 2
kernel.dmesg_restrict = 1
kernel.perf_event_paranoid = 3
kernel.yama.ptrace_scope = 2
EOF

    # Apply sysctl settings
    sysctl --system

    # Secure shared memory
    if ! grep -q "tmpfs /run/shm" /etc/fstab; then
        echo "tmpfs /run/shm tmpfs defaults,noexec,nosuid 0 0" >> /etc/fstab
    fi

    # Set secure permissions on important files
    chmod 600 /etc/crontab
    chmod 700 /etc/cron.d
    chmod 700 /etc/cron.daily
    chmod 700 /etc/cron.hourly
    chmod 700 /etc/cron.monthly
    chmod 700 /etc/cron.weekly

    log_success "System hardening applied"
}

#===============================================================================
# PostgreSQL Security
#===============================================================================

secure_postgresql() {
    log_info "Securing PostgreSQL..."

    # Ensure PostgreSQL only listens on localhost
    PG_CONF=$(find /etc/postgresql -name postgresql.conf 2>/dev/null | head -1)
    if [ -n "$PG_CONF" ]; then
        # Backup
        cp "$PG_CONF" "${PG_CONF}.backup.$(date +%Y%m%d)"

        # Set listen_addresses to localhost only
        sed -i "s/#listen_addresses = 'localhost'/listen_addresses = 'localhost'/" "$PG_CONF"
        sed -i "s/listen_addresses = '\*'/listen_addresses = 'localhost'/" "$PG_CONF"

        # Restart PostgreSQL
        systemctl restart postgresql

        log_success "PostgreSQL secured to localhost only"
    else
        log_warning "PostgreSQL config not found, skipping"
    fi
}

#===============================================================================
# Create Security Report
#===============================================================================

create_security_report() {
    log_info "Creating security report..."

    REPORT_FILE="/root/.wurm-tools/security-report.txt"
    mkdir -p /root/.wurm-tools

    cat > "$REPORT_FILE" <<EOF
================================================================================
WURM-TOOLS VPS Security Report
Generated: $(date)
================================================================================

FIREWALL STATUS (UFW)
---------------------
$(ufw status verbose)

FAIL2BAN STATUS
---------------
$(fail2ban-client status)

$(fail2ban-client status sshd 2>/dev/null || echo "SSH jail not active yet")

LISTENING PORTS
---------------
$(ss -tulpn | grep LISTEN)

ACTIVE CONNECTIONS
------------------
$(ss -tupn | head -20)

SSH CONFIGURATION
-----------------
PermitRootLogin: $(grep "^PermitRootLogin" /etc/ssh/sshd_config /etc/ssh/sshd_config.d/*.conf 2>/dev/null | tail -1)
PasswordAuthentication: $(grep "^PasswordAuthentication" /etc/ssh/sshd_config /etc/ssh/sshd_config.d/*.conf 2>/dev/null | tail -1 || echo "yes (default)")

INSTALLED SECURITY PACKAGES
---------------------------
$(dpkg -l | grep -E "fail2ban|ufw|unattended-upgrades" | awk '{print $2, $3}')

LAST LOGIN ATTEMPTS (Recent)
----------------------------
$(last -10)

FAILED LOGIN ATTEMPTS
---------------------
$(grep "Failed password" /var/log/auth.log 2>/dev/null | tail -10 || echo "No failed attempts logged")

================================================================================
RECOMMENDATIONS
================================================================================

1. Set up SSH key authentication and disable password login
2. Consider changing SSH port from default 22
3. Set up log monitoring (e.g., Logwatch)
4. Configure email alerts for security events
5. Regularly review this security report
6. Keep the system updated: apt update && apt upgrade

================================================================================
EOF

    chmod 600 "$REPORT_FILE"
    log_success "Security report saved to $REPORT_FILE"
}

#===============================================================================
# Print Summary
#===============================================================================

print_summary() {
    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║           SECURITY HARDENING COMPLETED!                     ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${BLUE}Security Measures Applied:${NC}"
    echo "  ✓ UFW Firewall (ports 22, 80, 443)"
    echo "  ✓ Fail2Ban (SSH brute-force protection)"
    echo "  ✓ SSH Hardening"
    echo "  ✓ Automatic Security Updates"
    echo "  ✓ Kernel Security Settings"
    echo "  ✓ PostgreSQL Localhost Only"
    echo ""
    echo -e "${YELLOW}Important:${NC}"
    echo "  • Set up SSH keys for passwordless authentication"
    echo "  • Then disable password authentication in SSH"
    echo "  • Review: /root/.wurm-tools/security-report.txt"
    echo ""
    echo -e "${BLUE}Useful Commands:${NC}"
    echo "  Check firewall:   ufw status"
    echo "  Check fail2ban:   fail2ban-client status"
    echo "  View banned IPs:  fail2ban-client status sshd"
    echo "  Unban IP:         fail2ban-client set sshd unbanip <IP>"
    echo ""
}

#===============================================================================
# Main
#===============================================================================

main() {
    print_banner
    check_root

    log_info "Starting security hardening..."
    echo ""

    setup_firewall
    setup_fail2ban
    harden_ssh
    setup_auto_updates
    harden_system
    secure_postgresql
    create_security_report

    print_summary
}

main "$@"
