#!/bin/bash
#===============================================================================
# WURM-TOOLS Application Deployment Script
# For Ubuntu 22.04/24.04 LTS on OVH VPS
#
# This script:
# - Clones or updates the application
# - Installs dependencies
# - Sets up environment configuration
# - Imports database schema
# - Builds and starts the application
#
# Usage: sudo bash 03-deploy-app.sh
#===============================================================================

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Configuration
APP_DIR="/var/www/wurm-tools"
REPO_URL="${REPO_URL:-https://github.com/Yarpii/WURM-TOOLS.git}"
BRANCH="${BRANCH:-main}"
DOMAIN="${DOMAIN:-blackforge.tools}"

#===============================================================================
# Helper Functions
#===============================================================================

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_banner() {
    echo -e "${CYAN}"
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║                                                            ║"
    echo "║   ██████╗ ███████╗██████╗ ██╗      ██████╗ ██╗   ██╗      ║"
    echo "║   ██╔══██╗██╔════╝██╔══██╗██║     ██╔═══██╗╚██╗ ██╔╝      ║"
    echo "║   ██║  ██║█████╗  ██████╔╝██║     ██║   ██║ ╚████╔╝       ║"
    echo "║   ██║  ██║██╔══╝  ██╔═══╝ ██║     ██║   ██║  ╚██╔╝        ║"
    echo "║   ██████╔╝███████╗██║     ███████╗╚██████╔╝   ██║         ║"
    echo "║   ╚═════╝ ╚══════╝╚═╝     ╚══════╝ ╚═════╝    ╚═╝         ║"
    echo "║                                                            ║"
    echo "║            Application Deployment Script v1.0              ║"
    echo "║                                                            ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        log_error "Please run as root (sudo bash $0)"
        exit 1
    fi
}

check_prerequisites() {
    log_info "Checking prerequisites..."

    # Check Node.js
    if ! command -v node &> /dev/null; then
        log_error "Node.js not installed. Run 01-initial-setup.sh first."
        exit 1
    fi

    # Check PM2
    if ! command -v pm2 &> /dev/null; then
        log_error "PM2 not installed. Run 01-initial-setup.sh first."
        exit 1
    fi

    # Check PostgreSQL
    if ! command -v psql &> /dev/null; then
        log_error "PostgreSQL not installed. Run 01-initial-setup.sh first."
        exit 1
    fi

    # Check for database credentials
    if [ ! -f /root/.wurm-tools/db-credentials.txt ]; then
        log_error "Database credentials not found. Run 01-initial-setup.sh first."
        exit 1
    fi

    log_success "All prerequisites met"
}

#===============================================================================
# Clone or Update Repository
#===============================================================================

setup_repository() {
    log_info "Setting up application repository..."

    if [ -d "${APP_DIR}/.git" ]; then
        log_info "Repository exists, pulling latest changes..."
        cd ${APP_DIR}

        # Stash any local changes
        git stash --include-untracked 2>/dev/null || true

        # Pull latest
        git fetch origin
        git checkout ${BRANCH}
        git pull origin ${BRANCH}

        log_success "Repository updated"
    else
        log_info "Cloning repository..."

        # Remove directory if it exists but is not a git repo
        rm -rf ${APP_DIR}

        # Clone
        git clone -b ${BRANCH} ${REPO_URL} ${APP_DIR}

        log_success "Repository cloned"
    fi

    cd ${APP_DIR}
}

#===============================================================================
# Setup Environment
#===============================================================================

setup_environment() {
    log_info "Setting up environment configuration..."

    # Load database credentials
    source /root/.wurm-tools/db-credentials.txt

    # Create .env.local file
    cat > ${APP_DIR}/.env.local <<EOF
# WURM-TOOLS Production Environment
# Generated by deploy script on $(date)

# Environment
NODE_ENV=production

# Database
DATABASE_URL=${DATABASE_URL}

# Application URL
NEXT_PUBLIC_APP_URL=https://${DOMAIN}

# Session (generate a unique secret)
SESSION_SECRET=$(openssl rand -base64 48)
EOF

    chmod 600 ${APP_DIR}/.env.local

    log_success "Environment configured"
}

#===============================================================================
# Install Dependencies
#===============================================================================

install_dependencies() {
    log_info "Installing Node.js dependencies..."

    cd ${APP_DIR}

    # Clean install
    rm -rf node_modules package-lock.json 2>/dev/null || true

    # Install production dependencies
    npm install

    log_success "Dependencies installed"
}

#===============================================================================
# Setup Database
#===============================================================================

setup_database() {
    log_info "Setting up database schema..."

    # Load database credentials
    source /root/.wurm-tools/db-credentials.txt

    # Check if schema already exists
    TABLES_EXIST=$(psql "${DATABASE_URL}" -t -c "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public';" 2>/dev/null | xargs)

    if [ "$TABLES_EXIST" -gt "0" ]; then
        log_warning "Database tables already exist (${TABLES_EXIST} tables found)"
        read -p "Do you want to reinitialize the schema? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log_info "Skipping schema import"
            return
        fi
    fi

    # Import schema
    if [ -f "${APP_DIR}/scripts/schema.sql" ]; then
        log_info "Importing PostgreSQL schema..."
        psql "${DATABASE_URL}" -f "${APP_DIR}/scripts/schema.sql"
        log_success "Database schema imported"
    else
        log_warning "Schema file not found at ${APP_DIR}/scripts/schema.sql"
    fi
}

#===============================================================================
# Build Application
#===============================================================================

build_application() {
    log_info "Building Next.js application..."

    cd ${APP_DIR}

    # Build for production
    npm run build

    log_success "Application built successfully"
}

#===============================================================================
# Setup PM2
#===============================================================================

setup_pm2() {
    log_info "Configuring PM2 process manager..."

    cd ${APP_DIR}

    # Create PM2 ecosystem config
    cat > ecosystem.config.js <<'EOF'
module.exports = {
  apps: [{
    name: 'wurm-tools',
    script: 'npm',
    args: 'start',
    cwd: '/var/www/wurm-tools',
    instances: 'max',
    exec_mode: 'cluster',
    autorestart: true,
    watch: false,
    max_memory_restart: '500M',
    env: {
      NODE_ENV: 'production',
      PORT: 3000
    },
    error_file: '/var/log/wurm-tools/error.log',
    out_file: '/var/log/wurm-tools/out.log',
    log_file: '/var/log/wurm-tools/combined.log',
    time: true
  }]
};
EOF

    # Create log directory
    mkdir -p /var/log/wurm-tools

    # Stop existing process if running
    pm2 stop wurm-tools 2>/dev/null || true
    pm2 delete wurm-tools 2>/dev/null || true

    # Start application
    pm2 start ecosystem.config.js

    # Save PM2 process list
    pm2 save

    log_success "Application started with PM2"
}

#===============================================================================
# Start Caddy
#===============================================================================

start_caddy() {
    log_info "Starting Caddy web server..."

    # Check if Caddy config is correct
    if caddy validate --config /etc/caddy/Caddyfile 2>/dev/null; then
        systemctl restart caddy
        log_success "Caddy started successfully"
    else
        log_error "Caddy configuration invalid. Please check /etc/caddy/Caddyfile"
        exit 1
    fi
}

#===============================================================================
# Verify Deployment
#===============================================================================

verify_deployment() {
    log_info "Verifying deployment..."

    # Wait for app to start
    sleep 5

    # Check PM2 status
    if pm2 show wurm-tools &>/dev/null; then
        log_success "PM2 process running"
    else
        log_error "PM2 process not running"
        pm2 logs wurm-tools --lines 50
        exit 1
    fi

    # Check if app responds
    if curl -s -o /dev/null -w "%{http_code}" http://localhost:3000 | grep -q "200\|304"; then
        log_success "Application responding on port 3000"
    else
        log_warning "Application not responding yet (may still be starting)"
    fi

    # Check Caddy status
    if systemctl is-active --quiet caddy; then
        log_success "Caddy web server running"
    else
        log_warning "Caddy not running"
    fi
}

#===============================================================================
# Print Summary
#===============================================================================

print_summary() {
    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║            DEPLOYMENT COMPLETED SUCCESSFULLY!               ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${BLUE}Application Details:${NC}"
    echo "  Directory:  ${APP_DIR}"
    echo "  Domain:     https://${DOMAIN}"
    echo "  Local URL:  http://localhost:3000"
    echo ""
    echo -e "${BLUE}PM2 Commands:${NC}"
    echo "  Status:     pm2 status"
    echo "  Logs:       pm2 logs wurm-tools"
    echo "  Restart:    pm2 restart wurm-tools"
    echo "  Stop:       pm2 stop wurm-tools"
    echo ""
    echo -e "${BLUE}Update Deployment:${NC}"
    echo "  cd ${APP_DIR} && git pull && npm install && npm run build && pm2 restart wurm-tools"
    echo ""
    echo -e "${YELLOW}Note:${NC}"
    echo "  Make sure DNS is pointing to this server for SSL to work."
    echo "  Caddy will automatically obtain Let's Encrypt certificates."
    echo ""
}

#===============================================================================
# Main
#===============================================================================

main() {
    print_banner
    check_root
    check_prerequisites

    log_info "Starting deployment for ${DOMAIN}..."
    echo ""

    setup_repository
    setup_environment
    install_dependencies
    setup_database
    build_application
    setup_pm2
    start_caddy
    verify_deployment

    print_summary
}

main "$@"
