-- WURM-TOOLS MySQL Schema - Part 15: Recipes
-- Run: mysql -u root -p wurmtools < 15-recipes.sql
-- Depends on: 03-crafting.sql

-- ========== RECIPES ==========
-- Recipe data is imported from game content database (22-game-content.sql)
-- via the migrate-recipes.js script.
--
-- The tables used are defined in 03-crafting.sql:
--   - items
--   - recipe_materials
--   - recipe_tools
--   - recipe_steps
--   - item_categories
--
-- No seed data is needed here.
