#!/bin/bash
# Combine all schema files into one complete schema
# Usage: ./combine-schema.sh > schema-complete.sql

echo "-- WURM-TOOLS Complete MySQL/MariaDB Schema"
echo "-- Generated: $(date)"
echo "-- This file is auto-generated from /scripts/schema/*.sql"
echo "-- DO NOT EDIT THIS FILE DIRECTLY - edit the individual schema files instead"
echo ""
echo "SET default_storage_engine=InnoDB;"
echo "SET NAMES utf8mb4;"
echo "SET CHARACTER SET utf8mb4;"
echo ""

# Combine all schema files in order
for file in /home/user/WURM-TOOLS/scripts/schema/*.sql; do
    echo ""
    echo "-- =============================================="
    echo "-- Source: $(basename "$file")"
    echo "-- =============================================="
    echo ""
    cat "$file"
done

echo ""
echo "-- Schema generation complete!"
